=== clintbellanger/mod-metadata/inventory-storage/ramls/schema/instance.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "publicationDate": {
      "type": "string",
      "pattern": "[0-9]{4}-[0-9]{2}-[0-9]{2}"
    },
    "identifiers": {
      "type": "array",
      "minItems": 0,
      "items": {
        "type": "object",
        "properties": {
          "namespace": {
            "type": "string"
          },
          "value": {
            "type": "string"
          }
        },
        "required": [
          "namespace",
          "value"
        ]
      }
    }
  },
  "required": [
    "title"
  ]
}

=== clintbellanger/mod-metadata/inventory-storage/ramls/examples/instance_get.json
{
  "id" : "601a8dc4-dee7-48eb-b03f-d02fdf0debd0",
  "title": "ADVANCING LIBRARY EDUCATION: TECHNOLOGICAL INNOVATION AND INSTRUCTIONAL DESIGN",
  "publicationDate": "2013-06-01",
  "identifiers": [
    {
      "namespace": "isbn",
      "value": "9781466636897"
    },
    {
      "namespace": "ybp",
      "value": "1"
    }
  ]
}
